import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  {
    ignores: [
      "coverage/**",
      "dist/**",
      "dist-vsix/**",
      "node_modules/**",
      "packages/*/dist/**",
      // Generated by scripts/bundle-extension.mjs; linting a bundle only
      // reports on the dependencies it inlined.
      "packages/vscode-extension/bundle/**"
    ]
  },
  {
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
        URL: "readonly"
      }
    }
  },
  js.configs.recommended,
  ...tseslint.configs.recommended
];
